servers = [
  {
    :name => "k8s-master",
    :type => "master",
    :eth1 => "192.168.10.10",
    :vcpu => "3",
    :mem => "4096"
  },
  {
    :name => "k8s-node1",
    :type => "node",
    :eth1 => "192.168.10.11",
    :vcpu => "1",
    :mem => "2048"
  },
  {
    :name => "k8s-node2",
    :type => "node",
    :eth1 => "192.168.10.12",
    :vcpu => "1",
    :mem => "2048"
  },
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
    config.vm.define machine[:name] do |config|
      config.vm.box = "geerlingguy/ubuntu1804"
      config.vm.box_version = "1.1.5"
      config.vm.hostname = machine[:name]
      config.vm.network :private_network, ip: machine[:eth1]

      config.vm.provider "virtualbox" do |v|
        v.name = machine[:name]
        v.memory = machine[:mem]
        v.cpus = machine[:vcpu]
      end

      config.vm.provision "ansible" do |ansible|
        if machine[:type] == "master"
          ansible.playbook = "master.yml"
        else
          ansible.playbook = "node.yml"
        end
        ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
      end
    end
  end
end
